### ISSUE TITLE
Swipe does not work in second activity

### ISSUE THREAD

**Issue by LightVolk** [pwittchen/swipe#12]
I use this library, but very confused: it does not swipe at second activity.

Here the link:
http://stackoverflow.com/questions/40823442/swipe-does-not-work-in-second-activity?noredirect=1#comment68869400_40823442

Can you help me?

**Comment by pwittchen** [comment]
I answered to your question on [StackOverflow](http://stackoverflow.com/a/40842411/1150795).

**Comment by pwittchen** [comment]
Problem is solved on SO, so I'm closing that issue.
