### ISSUE TITLE
Add support for RxJava 2

### ISSUE THREAD

**Issue by xsveda** [pwittchen/swipe#13]
The implementation will be almost the same, only `Subscriber<SwipeEvent>` need to be replaced by `ObservableEmitter<SwipeEvent>`.

**Comment by pwittchen** [comment]
Thanks for reporting this issue. 

I'm planning to add support for RxJava 2. I want to keep RxJava 1 module along with RxJava 2 because people still use Rx1. Moreover, I think it requires more changes than just replacing signature of the one method. For sure, sample apps require more updates.

Regards,
Piotr

**Comment by iRYO400** [comment]
Hello! Is there anybody? Cant compile. I've integrated RxJava2, so it throws me error 
```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
	File1: C:\Users\XXXX\.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjava\2.1.2\3efb75ac15c0659bc34f68d715930af8d57530a7\rxjava-2.1.2.jar
	File2: C:\Users\XXXX\.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.2.10\97c63ea14aa0626f626191b05012bdf529e57045\rxjava-1.2.10.jar
```

**Comment by pwittchen** [comment]
Hello,

This library is not compatible with RxJava2 yet. I have to find some time to perform an upgrade. In the meantime, you can use RxJava Interop libraries. Moreover, if you're using both RxJava1 and RxJava2 in your project, there may be a conflict.

**Comment by xsveda** [comment]
@iRYO400 Having RxJava1 a RxJava2 together in a project is not a problem, I used to have it for few months until complete project was migrated from RxJava1 -> RxJava2. The error you've posted is just a non-important packaging error, you may get rid of by excluding the `rxjava.properties` file from packing in your `build.gradle` file:
`    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
`

To make `Swipe` work together with RxJava2 you can
- Use RxJavaInterop library as @pwittchen suggested or
- Create your own `SwipeListener` that will map all `SwipeEvents` to RxJava2 `ObservableEmitter` like this:

```
    Observable
        .create(emitter -> swipe.setListener(createRxJava2SwipeListener(emitter)))
        .subscribe(event -> Log.d(TAG, "Event is " + event));

    private static SwipeListener createRxJava2SwipeListener(ObservableEmitter<SwipeEvent> emitter) {
        return new SwipeListener() {
            @Override void onSwipingLeft(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPING_LEFT);
            }

            @Override void onSwipedLeft(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPED_LEFT);
            }

            @Override void onSwipingRight(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPING_RIGHT);
            }

            @Override void onSwipedRight(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPED_RIGHT);
            }

            @Override void onSwipingUp(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPING_UP);
            }

            @Override void onSwipedUp(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPED_UP);
            }

            @Override void onSwipingDown(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPING_DOWN);
            }

            @Override void onSwipedDown(MotionEvent event) {
                emitter.onNext(SwipeEvent.SWIPED_DOWN);
            }
        };
    }
```

**Comment by pwittchen** [comment]
Library is migrated to RxJava2.x in #23 now. You can use RxJava1.x and RxJava2.x as a separate artifacts. See more in docs in `README.md`.
