### ISSUE TITLE
Placing swipe on fragments?

### ISSUE THREAD

**Issue by ramim94** [pwittchen/swipe#24]
How do I listen for swipes in fragments?

**Comment by pwittchen** [comment]
Only Activity has `boolean dispatchTouchEvent(MotionEvent event)` method, so I'd suggest creating swipe object inside the Activity and then pass its instance with the listener to the Fragment.

**Comment by ramim94** [comment]
I am awefully sorry for such a late reply, but I later ended up using activity instead of fragment and then I didn't try it on fragment again.
