### ISSUE TITLE
How to set Swipe on only 1 view and not others?

### ISSUE THREAD

**Issue by rosanlal26** [pwittchen/swipe#25]

**Comment by pwittchen** [comment]
What do you mean? Swipe gesture in this library is regarding Activity.
If you want to react on gestures in other Views you need to implement [dispatchTouchEvent](https://developer.android.com/reference/android/view/View.html#dispatchTouchEvent(android.view.MotionEvent)) method in a specific View in the same manner as in the Activity in the sample app.
