### ISSUE TITLE
Configurable distance / velocity

### ISSUE THREAD

**Issue by Skyost** [pwittchen/swipe#31]
Hi,

It would be great if the minimum swipe distance / velocity before a trigger could be configurable. Something like :

```java
Swipe swipe = new Swipe();
swipe.setDistance(100);
swipe.setVelocity(100);
swipe.setListener(new SwipeListener() {

	// Triggered if and only if the minimum distance and velocity are reached :

	@Override
	public void onSwipedLeft(final MotionEvent event) {}
	
	@Override
	public void onSwipedRight(final MotionEvent event) {}
	
	@Override
	public void onSwipedUp(final MotionEvent event) {}
	
	@Override
	public void onSwipedDown(final MotionEvent event) {}
	
	// Triggered the same way as before :

	@Override
	public void onSwipingLeft(final MotionEvent event) {}

	@Override
	public void onSwipingRight(final MotionEvent event) {}
	
	@Override
	public void onSwipingUp(final MotionEvent event) {}

	@Override
	public void onSwipingDown(final MotionEvent event) {}
	
});
```

**Comment by pwittchen** [comment]
Hi,

What do you mean by "distance" and "velocity"? Velocity of the finger motion on the screen? Distance from what? In what measurement units you would like to provide these values? I mean, what level of precision or accuracy do you expect?

Right now, swiped and swiping threshold is configurable. Here's the description: https://github.com/pwittchen/swipe#configuring-swipe-threshold. With that setting you can configure more or less sensitive swipe events.

**Comment by Skyost** [comment]
I mean velocity of the swipe and distance from the beginning of the swipe until the end (a bit like [this code](https://stackoverflow.com/a/19506010/3608831)).

But yes, I think it is the same as those thresholds ! So.... thank you 👍

**Comment by pwittchen** [comment]
Ok, so I think we can close it. :)
